FROM nginx
WORKDIR /
RUN mkdir /API
COPY /html/index.html /usr/share/nginx/html/
COPY installationDotNet.sh /
COPY start.sh /
COPY API /API
ADD installationDotNet.sh /docker-entrypoint.d
ADD start.sh /docker-entrypoint.d
RUN chmod +x /installationDotNet.sh
RUN chmod +x /start.sh
RUN ./installationDotNet.sh
COPY web.conf /etc/nginx/conf.d/web.conf
EXPOSE 80
CMD ["/start.sh"]
